name: boolean_selector
version: 2.1.0-dev
description: >-
  A flexible syntax for boolean expressions, based on a simplified version of
  Dart's expression syntax.
homepage: https://github.com/dart-lang/boolean_selector

environment:
  sdk: '>=2.9.0-1 <3.0.0'

dependencies:
  source_span: ^1.0.0
  string_scanner: ^1.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.2.0

dependency_overrides:
  # test: 1.11.1
  # test_api: 0.2.13
  # test_core: 0.2.18
  async:
    git:
      url: git://github.com/dart-lang/async.git
      ref: null_safety
  charcode:
    git:
      url: git://github.com/dart-lang/charcode.git
      ref: null_safety
  collection:
    git:
      url: git://github.com/dart-lang/collection.git
      ref: null_safety
  matcher:
    git:
      url: git://github.com/dart-lang/matcher.git
      ref: null_safety
  meta:
    git:
      url: git://github.com/dart-lang/sdk.git
      ref: null_safety-pkgs
      path: pkg/meta
  path:
    git:
      url: git://github.com/dart-lang/path.git
      ref: null_safety
  source_span:
    git:
      url: git://github.com/dart-lang/source_span.git
      ref: null_safety
  stack_trace:
    git:
      url: git://github.com/dart-lang/stack_trace.git
      ref: null_safety
  string_scanner:
    git:
      url: git://github.com/dart-lang/string_scanner.git
      ref: null_safety
  term_glyph:
    git:
      url: git://github.com/dart-lang/term_glyph.git
      ref: null_safety
  test_api:
    git:
      url: git://github.com/dart-lang/test.git
      ref: null_safety
      path: pkgs/test_api
  test_core:
    git:
      url: git://github.com/dart-lang/test.git
      ref: null_safety
      path: pkgs/test_core
  test:
    git:
      url: git://github.com/dart-lang/test.git
      ref: null_safety
      path: pkgs/test
